In [2]:
import torch

In [3]:
x = torch.arange(12)

In [4]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [7]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
y = torch.randn(2,3,4)

In [15]:
y.numel()

24

In [16]:
y.sum()

tensor(-0.1396)

In [17]:
before = id(y)
y += 1
y

tensor([[[ 0.4324,  1.0155,  1.0594, -0.2513],
         [ 0.3460,  2.3149,  0.8498,  0.7352],
         [ 0.5664,  0.8889,  2.3715,  1.8676]],

        [[ 0.9882,  1.6073,  2.1141,  1.0020],
         [ 1.2576, -0.8908,  0.9682,  1.2459],
         [ 1.5024,  1.2388, -1.0786,  1.7090]]])

In [18]:
before,id(y)

(3012456935648, 3012456935648)

In [19]:
x = torch.ones(2,3,4)
y+=x
before,id(y)

(3012456935648, 3012456935648)

In [20]:
y = y+x
before,id(y)

(3012456935648, 3012120359056)

In [24]:
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [25]:
x = torch.arange(12,dtype = torch.float32).reshape(3,4)

In [30]:
y =  torch.arange(12, dtype = torch.float32).reshape(3,4)
x >= y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [31]:
z = torch.zeros_like(y)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
z = torch.randn_like(y)
z

tensor([[-1.7613,  0.2505,  1.8319,  0.2331],
        [-2.2057, -1.5844, -1.1039, -0.4752],
        [-0.2177, -3.3045, -0.7857, -0.5982]])

In [38]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_filedata_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [40]:
import pandas as pd

data = pd.read_csv(data_file)

In [41]:
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [43]:
inputs ,outputs = data.iloc[:,0:2],data.iloc[:,2]

In [44]:
inputs

NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN

In [45]:
inputs.fillna(inputs.mean())

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [46]:
a = torch.arange(20).reshape(5,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [47]:
a.T


tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [50]:
b = a.clone()
c = a # a和c的地址是相同的，不会重新分配内存
id(a),id(b),id(c)

(3012479622896, 3012479678560, 3012479622896)

In [54]:
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [55]:
len(b),b.shape # len 只能计算第一个维度

(5, torch.Size([5, 4]))

In [56]:
b,b*b # 两个元素按位乘积

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121],
         [144, 169, 196, 225],
         [256, 289, 324, 361]]))

In [58]:
b,b.sum()

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor(190))

In [59]:
b,b.sum(axis = 0) # 按照哪个维度求和，哪个维度就会消失，也就是压缩了哪个维度

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([40, 45, 50, 55]))

In [63]:
b.sum(axis= 1,keepdim = True),b.sum(axis = 1)
# keepdim = True 就是非降维求和

(tensor([[ 6],
         [22],
         [38],
         [54],
         [70]]),
 tensor([ 6, 22, 38, 54, 70]))

In [64]:
b / b.sum(axis = 1,keepdim = True)
# 利用广播原理，对每个元素按照axis = 1 横轴方向进行求均值

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [68]:
b.cumsum(axis = 1),b.cumsum(axis = 0) # 这是进行累加求和，有点像前缀和的感觉

(tensor([[ 0,  1,  3,  6],
         [ 4,  9, 15, 22],
         [ 8, 17, 27, 38],
         [12, 25, 39, 54],
         [16, 33, 51, 70]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  6,  8, 10],
         [12, 15, 18, 21],
         [24, 28, 32, 36],
         [40, 45, 50, 55]]))

In [69]:
a = torch.arange(12).reshape(3,4)
b = torch.arange(4)

In [80]:
x = torch.arange(3)
y = x.clone()
torch.dot(x,y) # dot是两个维度相同的向量进行乘积

tensor(5)

In [72]:
a,b,torch.mv(a,b) # 矩阵和向量的点积
# 相当于矩阵的每行都与向量乘积然后然后求和 所以矩阵的列维度必须和向量的维度对应起来，才能×

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([0, 1, 2, 3]),
 tensor([14, 38, 62]))

In [81]:
c = torch.arange(12).reshape(4,3)
torch.mm(a,c) # 矩阵的乘法，中间相等取两边

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262]])

### 范式
- L1 范式 向量元素的绝对值之和
- L2 范式 向量到原点的距离 向量平方和的平方根
  

In [82]:
# l1
torch.abs(c).sum()

tensor(66)

In [95]:
d = torch.arange(40).reshape(2,5,4)
d

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [99]:
x = d.sum(axis = 1)
x,x.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

### 自动求导

In [100]:
x = torch.arange(4.0)

In [110]:
x.requires_grad_(True)
x.grad

In [111]:
# 函数是y = 2*x
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [115]:
x.grad 

tensor([ 0.,  4.,  8., 12.])

In [116]:
x.grad== 4*x

tensor([True, True, True, True])

In [117]:
torch.dot(x,x)

tensor(14., grad_fn=<DotBackward0>)

### 线性回归

In [121]:
%matplotlib inline 
# 表示在使用matplotlib 的时候内嵌在jupyter里面
import random
import torch
import math
import numpy as np
import time
from d2l import torch as d2l

In [ ]:
# 构建数据集
def synthetic_data(w,b,num_examples):
    # 生成y = wx + b + e
    X = torch